AWSTemplateFormatVersion: '2010-09-09'
Description: Hedge OpenSearch instance using the smallest node type (t3.small.search) with fine-grained access control.

Resources:
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'RtcCognitoOpenSearchRole${EnvironmentNameCamelCase}${VendorSuffixCamelCase}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "opensearchservice.amazonaws.com"
            Action: "sts:AssumeRole"

      Policies:
        - PolicyName: !Sub 'RtcCognitoOpenSearchAccess${EnvironmentNameCamelCase}${VendorSuffixCamelCase}'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cognito-idp:DescribeUserPool"
                  - "cognito-idp:CreateUserPoolClient"
                  - "cognito-idp:DescribeUserPoolClient"
                  - "cognito-identity:DescribeIdentityPool"
                  - "cognito-identity:ListIdentityPools"
                Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/rtc-classifieds-${EnvironmentName}-${VendorSuffix}/*'

        - PolicyName: AllowCognitoActions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttp*'
                Resource:
                  - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}'
                  - !Sub 'arn:aws:cognito-identity:${AWS::Region}:${AWS::AccountId}:identitypool/${IdentityPoolId}'
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Sub 'rtc-classifieds-${EnvironmentName}-${VendorSuffix}'
      EngineVersion: OpenSearch_2.19
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      EncryptionAtRestOptions:
        Enabled: true # Enable encryption at rest
      NodeToNodeEncryptionOptions:
        Enabled: true # Enable node-to-node encryption
      DomainEndpointOptions:
        EnforceHTTPS: true # Enable HTTPS enforcement
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  EnvironmentName:
    Description: The name of the environment (e.g., dev, prod)
    Type: String
  EnvironmentNameCamelCase:
    Description: The name of the environment (e.g., dev, prod) in CamelCase for supporting multiple environments in same account without conflicts.
    Type: String
  VendorSuffix:
    Description: Unique vendor suffix for the bucket.
    Type: String
  VendorSuffixCamelCase:
    Description: Unique vendor suffix in CamelCase for supporting multiple vendors under the same account.
    Type: String
  UserPoolId:
    Description: The ID of the Cognito User Pool
    Type: String
  IdentityPoolId:
    Description: The ID of the Cognito Identity Pool
    Type: String
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

Outputs:
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain
    Value: !GetAtt OpenSearchDomain.DomainEndpoint