service: goclassifieds-versait-api
frameworkVersion: '3'
plugins:
  - serverless-prune-plugin
  - serverless-custom-packaging-plugin
custom:
  githubToken: ${file(./private.${opt:stage, 'dev'}.json):githubToken}
  versaitUsername: ${file(./private.${opt:stage, 'dev'}.json):versaitUsername}
  webhookSecret: ${file(./private.${opt:stage, 'dev'}.json):webhookSecret}
  openAiApiKey: ${file(./private.${opt:stage, 'dev'}.json):openAiApiKey}
provider:
  name: aws
  runtime: provided.al2023
  memorySize: 512
  timeout: 45
  #logs:
    #websocket: true
  httpApi:
    payload: '1.0'
    cors: true
package:
  individually: true
resources:
  Resources:
    VersaitRole:
      Type: AWS::IAM::Role
      Properties:
        Path: "/"
        RoleName: verait-${opt:region, 'us-east-1'}-lambdaRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole   
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: goclassifieds-versait-api-lambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogGroups
                    - logs:DescribeLogStreams
                    - logs:GetLogEvents
                    - logs:FilterLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: "Allow"
                  Action:
                    - "lambda:InvokeFunction"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                    - "execute-api:ManageConnections"
                  Resource: "*"
functions:
  VersaitApi:
    handler: bootstrap
    role: VersaitRole
    package:
      path: bazel-bin/api/versait
      artifact: .serverless/VersaitApi.zip
      libs: api/entity
      include_globs:
        - "**/bootstrap"
        - "**/*.json.tmpl"
        - "**/*.pem"
    environment:
      GITHUB_TOKEN: ${self:custom.githubToken}
      VERSAIT_USERNAME: ${self:custom.versaitUsername}
      OPENAI_API_KEY: ${self:custom.openAiApiKey}
      #WEBHOOK_SECRET: ${self:custom.webhookSecret}
      STAGE: ${opt:stage, 'dev'}
    events:
      - httpApi:
          path: /versait/{proxy+}
          method: POST